development:
  adapter: postgresql
  encoding: unicode
  database: lamebook_development
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: lamebook_testing
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: lamebook_production
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
